'use client';
import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase/client';

type Product = { id: string; name: string; quantity: number; low_stock_threshold: number };
type Sale = { id: string; total: number | string; created_at: string };
type SaleItem = { quantity: number; products: { name: string } | null };
type Promotion = { id: string; name: string; code: string; discount_type: 'percent' | 'fixed'; discount_value: number };

export function Dashboard() {
  const [sales, setSales] = useState<Sale[]>([]); const [lowStock, setLowStock] = useState<Product[]>([]); const [promotions, setPromotions] = useState<Promotion[]>([]); const [topProduct, setTopProduct] = useState<{ name: string; units: number } | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const client = supabase(); const start = new Date(); start.setHours(0, 0, 0, 0); const since = start.toISOString();
    const [salesResult, productsResult, itemsResult, promotionsResult] = await Promise.all([client.from('sales').select('id,total,created_at').gte('created_at', since), client.from('products').select('id,name,quantity,low_stock_threshold').eq('is_active', true), client.from('sale_items').select('quantity,products(name),sales!inner(created_at)').gte('sales.created_at', since), client.from('promotions').select('id,name,code,discount_type,discount_value').eq('active', true).order('created_at', { ascending: false }).limit(4)]);
    const currentSales = (salesResult.data ?? []) as Sale[]; setSales(currentSales); setLowStock(((productsResult.data ?? []) as Product[]).filter(p => p.quantity <= p.low_stock_threshold)); setPromotions((promotionsResult.data ?? []) as Promotion[]); const grouped = new Map<string, number>(); const items = (itemsResult.data ?? []) as unknown as SaleItem[]; items.forEach(item => { const name = item.products?.name; if (name) grouped.set(name, (grouped.get(name) ?? 0) + item.quantity); }); const winner = [...grouped.entries()].sort((a, b) => b[1] - a[1])[0]; setTopProduct(winner ? { name: winner[0], units: winner[1] } : null); setLoading(false);
  }, []);
  useEffect(() => { load(); const channel = supabase().channel('dashboard-sales').on('postgres_changes', { event: '*', schema: 'public', table: 'sales' }, load).subscribe(); return () => { supabase().removeChannel(channel); }; }, [load]);
  const total = sales.reduce((sum, sale) => sum + Number(sale.total), 0);
  if (loading) return <div className="grid gap-4 md:grid-cols-3"><Skeleton/><Skeleton/><Skeleton/></div>;
  return <section className="mx-auto max-w-6xl px-5 py-10"><div className="mb-7"><p className="text-sm font-semibold text-blue-600">PANEL EN VIVO</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Resumen de hoy</h1><p className="mt-2 text-slate-500">Los indicadores se actualizan cuando registras una venta.</p></div><div className="grid gap-4 md:grid-cols-3"><Metric label="Ventas de hoy" value={`$${total.toLocaleString('es-MX', { minimumFractionDigits: 2 })}`} detail={`${sales.length} transacciones`} tone="blue"/><Metric label="Alertas de stock" value={String(lowStock.length)} detail={lowStock.length ? lowStock.map(p => p.name).slice(0, 2).join(', ') : 'Todo bajo control'} tone="amber"/><Metric label="Producto más vendido" value={topProduct?.name ?? 'Sin ventas aún'} detail={topProduct ? `${topProduct.units} unidades vendidas` : 'Comienza a vender para verlo aquí'} tone="teal"/></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Actividad reciente</h2>{sales.length ? <div className="mt-4 space-y-3">{sales.slice(0, 5).map(sale => <div key={sale.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span className="text-sm text-slate-600">Venta registrada</span><strong>${Number(sale.total).toFixed(2)}</strong></div>)}</div> : <Empty text="Aún no hay ventas registradas hoy."/>}</article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Stock requiere atención</h2>{lowStock.length ? <div className="mt-4 space-y-3">{lowStock.slice(0, 5).map(p => <div key={p.id} className="flex justify-between text-sm"><span>{p.name}</span><span className="font-semibold text-rose-600">{p.quantity} disponibles</span></div>)}</div> : <Empty text="No tienes productos con bajo stock."/>}</article></div><article className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Promociones activas</h2>{promotions.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{promotions.map(promotion => <div key={promotion.id} className="rounded-xl bg-blue-50 p-4"><p className="font-semibold text-blue-950">{promotion.name}</p><p className="mt-1 text-sm text-blue-700">Código {promotion.code}</p><p className="mt-2 text-sm text-slate-600">{promotion.discount_type === 'percent' ? `${promotion.discount_value}% de descuento` : `$${Number(promotion.discount_value).toFixed(2)} de descuento`}</p></div>)}</div> : <Empty text="No hay promociones activas por ahora."/>}</article></section>;
}
function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: 'blue' | 'amber' | 'teal' }) { const colors = { blue: 'bg-blue-50 text-blue-700', amber: 'bg-amber-50 text-amber-700', teal: 'bg-teal-50 text-teal-700' }; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`inline-flex rounded-lg px-2 py-1 text-xs font-semibold ${colors[tone]}`}>{label}</span><p className="mt-4 truncate text-2xl font-bold">{value}</p><p className="mt-2 truncate text-sm text-slate-500">{detail}</p></article>; }
function Empty({ text }: { text: string }) { return <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">{text}</p>; }
function Skeleton() { return <div className="h-40 animate-pulse rounded-2xl bg-slate-200" />; }
